name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches: ["master"] # Trigger on pushes to main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with: { node-version: "20", cache: "npm" }
      - run: npm ci
      - run: npm run build-storybook # Ensure this outputs to storybook-static
      - uses: actions/upload-pages-artifact@v3
        with: { path: "storybook-static" }
      - id: deploy
        uses: actions/deploy-pages@v4
